import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How PulseUp collects, uses, and protects your data.",
};

const UPDATED = "August 4, 2026";
const CONTACT_EMAIL = "privacy@pulseup.io";

export default function PrivacyPolicyPage() {
  return (
    <LegalPage title="Privacy Policy" updated={UPDATED}>
      <p>
        This Privacy Policy explains how PulseUp (&ldquo;PulseUp&rdquo;, &ldquo;we&rdquo;,
        &ldquo;us&rdquo;) collects, uses, discloses, and safeguards your information when you use
        our mobile application and website (together, the &ldquo;Service&rdquo;). By using the
        Service, you agree to the collection and use of information in accordance with this
        policy.
      </p>

      <h2>1. Information We Collect</h2>
      <p>We collect information you provide directly and information generated by your use of the Service:</p>
      <ul>
        <li>
          <strong>Account information:</strong> name, email address, username, profile photo, and
          password (stored in hashed form) when you register directly with an email and password.
        </li>
        <li>
          <strong>Google Sign-In:</strong> if you choose to sign in with Google, Google shares your
          name, email address, profile picture, and a unique account identifier with us so we can
          create and authenticate your PulseUp account. We do not receive your Google password and
          do not access any other Google service on your behalf. You can review or revoke
          PulseUp&rsquo;s access to your Google account at any time in your{" "}
          <a href="https://myaccount.google.com/permissions" target="_blank" rel="noreferrer">
            Google Account settings
          </a>
          .
        </li>
        <li>
          <strong>Fitness and health data:</strong> workouts, exercises, sets, reps, cardio
          sessions, GPS location during live-tracked activities, heart rate and other data synced
          from connected wearables, streaks, XP, and achievements.
        </li>
        <li>
          <strong>Social content:</strong> posts, reactions, comments, crew memberships, and other
          content you choose to share within the app.
        </li>
        <li>
          <strong>Device and usage data:</strong> device model, operating system, app version, IP
          address, crash logs, and analytics events (e.g. via Google Analytics) describing how you
          interact with the Service.
        </li>
      </ul>

      <h2>2. How We Use Your Information</h2>
      <ul>
        <li>Provide, operate, and maintain the Service, including social and gamification features (Crew, Party Workout, Live Cardio, XP, streaks, and achievements).</li>
        <li>Personalize your experience and training recommendations.</li>
        <li>Communicate with you, including service updates and, where permitted, marketing messages you can opt out of.</li>
        <li>Monitor and analyze usage and trends to improve the Service.</li>
        <li>Detect, prevent, and address technical issues, fraud, or abuse.</li>
        <li>Comply with legal obligations.</li>
      </ul>

      <h2>3. Location Data</h2>
      <p>
        Live Cardio and similar features use precise GPS location to track your route, pace, and
        distance in real time. Location is only collected while the corresponding feature is
        active and can be disabled at any time in your device settings, though this will limit
        related features.
      </p>

      <h2>4. Sharing of Information</h2>
      <p>We do not sell your personal information. We may share information with:</p>
      <ul>
        <li>
          Other users, to the extent you choose to share content socially (e.g. crew members
          seeing your workout feed).
        </li>
        <li>
          Service providers who process data on our behalf, such as cloud hosting (Google Cloud),
          authentication (Firebase), and analytics (Google Analytics).
        </li>
        <li>Law enforcement or regulators when required by law.</li>
        <li>A successor entity in connection with a merger, acquisition, or sale of assets.</li>
      </ul>

      <h2>5. Data Retention and Deletion</h2>
      <p>
        We retain your information for as long as your account is active or as needed to provide
        the Service. You can delete your account at any time from the app under Settings &gt;
        Account &gt; Delete Account. Deleting your account immediately deactivates it and
        anonymizes your email address so it can no longer be used to sign in or identify you.
        Underlying records (such as workout history and social content) are retained only as
        needed for legal, security, or operational purposes after deletion. You can request full
        erasure of any remaining data by contacting us at{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>

      <h2>6. Data Security</h2>
      <p>
        We use industry-standard technical and organizational measures to protect your
        information. No method of transmission or storage is 100% secure, and we cannot guarantee
        absolute security.
      </p>

      <h2>7. Your Rights</h2>
      <p>
        Depending on your jurisdiction (including under Brazil&rsquo;s LGPD, the EU&rsquo;s GDPR,
        or the CCPA), you may have the right to access, correct, export, or delete your personal
        data, and to withdraw consent for optional processing. You can manage most of this
        directly in the app under Settings, or by contacting us at{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>

      <h2>8. Children&rsquo;s Privacy</h2>
      <p>
        The Service is not directed to children under 13 (or the minimum age required in your
        country), and we do not knowingly collect personal information from them. If you believe a
        child has provided us with personal information, please contact us so we can remove it.
      </p>

      <h2>9. International Transfers</h2>
      <p>
        Your information may be processed and stored in countries other than your own, including
        the United States, where our service providers operate. We take steps to ensure your data
        receives an adequate level of protection wherever it is processed.
      </p>

      <h2>10. Changes to This Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. We will notify you of material
        changes by updating the &ldquo;Last updated&rdquo; date above and, where appropriate,
        through the app or by email.
      </p>

      <h2>11. Contact Us</h2>
      <p>
        If you have questions about this Privacy Policy, contact us at{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>
    </LegalPage>
  );
}
